defaults: 
  - default
  - _self_

hydra:
  searchpath:
    - file://src/configs/train/hp


# uv run src/hp.py --multirun hp=baseline,net_256,net_256x3,net_512
# uv run src/hp.py --multirun hp=batchsize_6144,batchsize_1024,batchsize_512,batchsize_256,baseline
