name: baseline

net_arch:
  pi: [256, 256]
  vf: [256, 256]

steps: 5000_0000
n_steps: 5000
batch_size: 500

max_cycles: 500
learning_rate: 2e-4

seed: 42

# Env Settings
use_angle_reward: False
use_f_disturbance: False
use_f_obs: False

use_package_mass_obs: False
use_package_mass_disturbance: False

agent_num: 3