defaults:
  # - setting: 250327_mappo #1552_mappohappo
  - setting: 1552_mappohappo
  # - override hydra/launcher: submitit_local
  - _self_


# hydra:
#   launcher:
#     timeout_min: 6000
#     gpus_per_node: 0